### ISSUE TITLE
getting error while using jio.sh

### ISSUE THREAD

**Issue by gyandoo** [swappyison/JiocinemaDownloader#11]
getting the error below when trying to use the bulk download, pl. help

````
Bigg Boss OTT - S01E04 - Akshara's Bigg outburst!

MPD URL: https://jc-ak-dashstreaming.jiocinema.com/content/entry/wvdata/68/65/f2d133f0fac511ebaaa96b52e9e94b20_voot_web_premium_1635539590084.mpd?hdnts=st=1696148031~exp=1696148631~acl=/content/entry/wvdata/68/65/*~id=a0cb45eb-45cc-4b10-97de-d132fa28fdb2~hmac=ae1265daab53325a92c3976d17d265eb73d6782d3229deb1b688033e5dca740f

[generic] Extracting URL: https://jc-ak-dashstreaming.jiocinema.com/content/entry/wvdata/68/65/f2d133f0fac511ebaaa96b52e9e9...deb1b688033e5dca740f
[generic] *~id=a0cb45eb-45cc-4b10-97de-d132fa28fdb2~hmac=ae1265daab53325a92c3976d17d265eb73d6782d3229deb1b688033e5dca740f: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] *~id=a0cb45eb-45cc-4b10-97de-d132fa28fdb2~hmac=ae1265daab53325a92c3976d17d265eb73d6782d3229deb1b688033e5dca740f: Extracting information
ERROR: [generic] *~id=a0cb45eb-45cc-4b10-97de-d132fa28fdb2~hmac=ae1265daab53325a92c3976d17d265eb73d6782d3229deb1b688033e5dca740f: This video is DRM protected
An error occurred: ERROR: [generic] *~id=a0cb45eb-45cc-4b10-97de-d132fa28fdb2~hmac=ae1265daab53325a92c3976d17d265eb73d6782d3229deb1b688033e5dca740f: This video is DRM protected

```

**Comment by gyandoo** [comment]
changed '`jiobulkdownloaderDRM.py`' in `jio.sh`

now getting the '`N_m3u8DL-RE`' error due to linux :/

```
sh /home/red/Downloads/WKS/jio.sh 
Enter the show ID: 3499723


/usr/local/lib/python3.9/dist-packages/urllib3/connectionpool.py:1045: InsecureRequestWarning: Unverified HTTPS request is being made to host 'apis-jiovoot.voot.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

Bigg Boss - S04E01 - Buntyː The new house captain

/usr/local/lib/python3.9/dist-packages/urllib3/connectionpool.py:1045: InsecureRequestWarning: Unverified HTTPS request is being made to host 'jc-ak-dashstreaming.jiocinema.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
AAAALXBzc2gAAAAA7e+LqXnWSs6jyCfc1R0h7QAAAA0iBSAAQJU3SOPclZsG

/usr/local/lib/python3.9/dist-packages/urllib3/connectionpool.py:1045: InsecureRequestWarning: Unverified HTTPS request is being made to host 'prod.media.jio.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
--key 281b01ddf87058c5af55166bc00eb661:e95091bf261632d8ec708aca5545a132
--key c02ff1b0293554d0b4414f0e08a60ce3:1de1d986b9cf1164bd32e42182911e17
--key 4ffddf6c56425f9eab3eb6b82835709c:4f249a1deb2402647979be4e295f4bbc

Traceback (most recent call last):
  File "/home/red/Downloads/WKS/jiobulkdownloaderDRM.py", line 182, in <module>
    main()
  File "/home/red/Downloads/WKS/jiobulkdownloaderDRM.py", line 161, in main
    subprocess.run([m3u8DL_RE,
  File "/usr/lib/python3.9/subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1823, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'N_m3u8DL-RE'

```

**Comment by gyandoo** [comment]
tried after installing

`pip3 install m3u8dl`

no joy :/

**Comment by gyandoo** [comment]
works well with windows
