### ISSUE TITLE
getting error using jiodownloader.py

### ISSUE THREAD

**Issue by gyandoo** [swappyison/JiocinemaDownloader#12]
```
python3 '/home/red/Downloads/WKS/jiodownloader.py' 

test link: https://www.jiocinema.com/movies/sergeant-bhojpuri/3767689
test link: https://www.jiocinema.com/tv-shows/kaalkoot/1/janam-din/3788001

link: https://www.jiocinema.com/tv-shows/bigg-boss/13/bigg-boss/3641243

Bigg Boss - S13E77 - Bigg Boss

AAAALXBzc2gAAAAA7e+LqXnWSs6jyCfc1R0h7QAAAA0iBSAAInYGSOPclZsG

--key 56e4d0ac5fe8538f9c1716822ffec73d:035993313e7ef511c7c22526c7a79c00
--key 4cb8654d7678553e87189b336bbd4225:c64db827b044d9a28ff66d72054d8af6
--key 2b2b7c5c714158d29222d14b4e83483c:3efcac268c7b588955ff72e916f9c36d

Traceback (most recent call last):
  File "/home/red/Downloads/WKS/jiodownloader.py", line 169, in <module>
    subprocess.run([m3u8DL_RE,
  File "/usr/lib/python3.9/subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1823, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'N_m3u8DL-RE'
```

**Comment by gyandoo** [comment]
i just realized it is to run 'N_m3u8DL-RE.exe' but im on linux, 

i tried placing [https://github.com/nilaoda/N_m3u8DL-RE/releases/tag/v0.2.0-beta](https://github.com/nilaoda/N_m3u8DL-RE/releases/tag/v0.2.0-beta) in the same folder, the linux version,  N_m3u8DL-RE_Beta_linux-x64_20230628.tar.gz 

no joy :/

**Comment by gyandoo** [comment]
works great with windows
