### ISSUE TITLE
getting an error on windows 11

### ISSUE THREAD

**Issue by spice42** [swappyison/JiocinemaDownloader#19]
```
Traceback (most recent call last):
  File "C:\Users\PC\AppData\Local\Programs\Python\Python311\Lib\site-packages\jwt\api_jwt.py", line 178, in _decode_payload
    payload = json.loads(decoded["payload"])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PC\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 341, in loads
    s = s.decode(detect_encoding(s), 'surrogatepass')
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x88 in position 357: invalid start byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\PC\WKS-KEYS\jiobulkdownloaderDRM.py", line 193, in <module>
    main()
  File "C:\Users\PC\WKS-KEYS\jiobulkdownloaderDRM.py", line 31, in main
    decoded = jwt.decode(access_token, options={"verify_signature": False})
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PC\AppData\Local\Programs\Python\Python311\Lib\site-packages\jwt\api_jwt.py", line 210, in decode
    decoded = self.decode_complete(
              ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PC\AppData\Local\Programs\Python\Python311\Lib\site-packages\jwt\api_jwt.py", line 159, in decode_complete
    payload = self._decode_payload(decoded)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PC\AppData\Local\Programs\Python\Python311\Lib\site-packages\jwt\api_jwt.py", line 180, in _decode_payload
    raise DecodeError(f"Invalid payload string: {e}")
jwt.exceptions.DecodeError: Invalid payload string: 'utf-8' codec can't decode byte 0x88 in position 357: invalid start byte
```

**Comment by swappyison** [comment]
pip install pyjwt

**Comment by spice42** [comment]
not working :(

is there a way I can reach you via email, thanks
