### ISSUE TITLE
pywidevine

### ISSUE THREAD

**Issue by sarvottam99** [swappyison/JiocinemaDownloader#2]
if pywidevine is not installed - 
Traceback (most recent call last):
  File "D:\TV and Web Series\JiocinemaDownloader-main\jiodownloader.py", line 126, in <module>
    from pywidevine.L3.cdm import cdm, deviceconfig
ModuleNotFoundError: No module named 'pywidevine'

if pywidevine is installed - 
Traceback (most recent call last):
  File "D:\TV and Web Series\JiocinemaDownloader-main\jiodownloader.py", line 126, in <module>
    from pywidevine.L3.cdm import cdm, deviceconfig
ModuleNotFoundError: No module named 'pywidevine.L3'

**Comment by swappyison** [comment]
just move all the python scripts inside WKS-KEYS folder. it will solve the problem

**Comment by Harshilmehta23** [comment]
Thanks for all the work,

I am having below error while running 'python3 jiodownloader.py':

```
Traceback (most recent call last):
  File "C:\Users\User\Documents\JiocinemaDownloader\WKS-KEYS(4)\jiodownloader.py", line 137, in <module>
    from pywidevine.L3.cdm import cdm, deviceconfig
ModuleNotFoundError: No module named 'pywidevine.L3'
```

I tried moving all the Python scripts inside WKS-KEYS folder. but the issue still persists.

@sarvottam99 were you able to solve the problem?
